# Generated by Django 4.2.20 on 2025-04-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
