# Generated by Django 4.2.20 on 2026-03-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_remove_profile_user_profile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.UUIDField(),
        ),
    ]
