# Generated by Django 4.2.20 on 2025-04-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='super_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
