# Generated by Django 4.2.20 on 2025-04-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_organization_super_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='super_user',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
