# Generated by Django 4.2.20 on 2025-04-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_user_task_users_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='project',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='project',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='task',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='user',
            field=models.IntegerField(),
        ),
    ]
