# Generated by Django 4.2.20 on 2026-07-03 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_task_issue_type_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='Task',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='Task_Comment',
            new_name='task_comment',
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('PROJECT_ASSIGNED', 'Project Assigned'), ('ORG_UPDATE', 'Organization Update'), ('TASK_COMMENT', 'Task Comment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.project'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='work_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.taskcomment'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='super_user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='tasks_notif_user_id_9ee72a_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='tasks_organ_is_acti_e93a22_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['super_user'], name='tasks_organ_super_u_d66ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='tasks_proje_status_ecb090_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active'], name='tasks_proje_is_acti_1beff5_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['super_user'], name='tasks_proje_super_u_a01d68_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project'], name='tasks_task_project_5a0702_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['users'], name='tasks_task_users_bf87c7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='tasks_task_priorit_a900d4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_active'], name='tasks_task_is_acti_16b97a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task'], name='tasks_taskc_task_508fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['project'], name='tasks_taskc_project_63dba5_idx'),
        ),
    ]
